### ISSUE TITLE
Avoid uploading .docx file over github

### ISSUE THREAD

**Issue by sagnik20** [subhayu99/Azure-telemetry-service#1]
Hey! ⭐ 
Its great that you have used Azure Telemetry service. But it seems you uploaded the documentation in docx format that too without any valid signatures in it. Please avoid doing so and rather upload your source code or relevant documents.
Thanks 😃

**Comment by subhayu99** [comment]
Now is this OK? 
https://github.com/subhayu99/Azure-telemetry-service
